#ifndef MESTIMATE_SIDECAR_H
#define MESTIMATE_SIDECAR_H

#define MESTIMATE_SCHEMA_NAME "mestimate-sidecar"
#define MESTIMATE_SCHEMA_VERSION "v1"
#define MESTIMATE_DEFAULT_METHOD "epzs"
#define MESTIMATE_DEFAULT_MB_SIZE 16
#define MESTIMATE_DEFAULT_SEARCH_PARAM 12
#define MESTIMATE_COHERENCE_EPSILON 1e-12

#endif
